title: Use Cases

description: The documentation website for the FINOS FDC3 Use Cases

google_analytics: UU-123456

show_downloads: false

github:
  is_project_page: true
  repository_url: https://github.com/fdc3/use-cases

version: '[[tag]]'

menu_collection: 'use_cases'

collections:
- tags
- use_cases

links:
  - name: Use Case Working Group
    url: /

social_icons:
  - name: github
    image_url: "https://www.finos.org/hs-fs/hubfs/FINOS/website/logos/social-logos/github-logo-black.png?t=1539813516681&amp;width=48&amp;height=48&amp;name=github-logo.png"
    link_url: https://github.com/fdc3/use-cases
  - name: confluence
    image_url: "https://www.finos.org/hs-fs/hubfs/sofin%20assets/External%20logos/atlassian-logo.png?width=48&amp;height=48&amp;name=atlassian-logo.png"
    link_url: https://finosfoundation.atlassian.net/wiki/spaces/FDC3/pages/169738241/Use+Case+Working+Group